from __future__ import annotations

"""Append-only, hash-chained JSONL audit helper for tests.

The product audit trail lives in ``ledger.sqlite`` via ``ledger.store``. This
module is retained for isolated audit-chain tests and one-off fixture conversion
utilities that need to verify JSONL hash-chain behavior.

Each record is a JSON object on a single line.  The chain is maintained by
storing ``prev``: the SHA-256 hex digest of the **raw line bytes** of the
preceding record.  The first record uses 64 hex zeros as its ``prev``.

Record types
------------
intent          Atomic-write intent: ledger mutation is about to begin.
ledger-sealed   Projection write complete: SHA-256 of generated bytes.
entry-written   A transaction entry was appended.
pending-staged  A pending transaction was written to staging.
pending-dropped A pending was removed from staging (superseded / purged).
acknowledged    Owner acknowledged a ledger-hash mismatch: sha256 of diff.
ratified        Owner ratified a git-authored diff: commit hash + author.

API
---
AuditLog(path)              Load (or start) an audit log at *path*.
log.append(record_type, **fields) -> None
    Append a record with auto-computed ``prev``, ``type``, and ``ts``.
    ``ts`` defaults to utcnow(); supply ``ts=<iso_string>`` for
    deterministic tests.
log.tail(n=10) -> list[dict]
    Return the last *n* raw records as parsed dicts.
log.last_sealed() -> dict | None
    Return the most-recent ``ledger-sealed`` record (skip trailing
    acknowledgement / ratification records that may follow it).
log.last_intent() -> dict | None
    Return the most-recent ``intent`` record.
log.has_seal_for_intent(intent_record) -> bool
    True when a ``ledger-sealed`` record that post-dates *intent_record*
    exists in the log.
verify_chain(path) -> list[str]
    Read *path* and return a list of error strings (empty = valid).
"""

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# 64 hex zeros — the sentinel ``prev`` for the first record.
_GENESIS_PREV = "0" * 64


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_line(line: str) -> str:
    """SHA-256 of the raw UTF-8 bytes of *line* (without trailing newline)."""
    return _sha256_bytes(line.encode("utf-8"))


def _now_iso() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class AuditLog:
    """Append-only audit log backed by a JSONL file.

    All writes go through ``append``; direct file manipulation is unsafe.
    """

    def __init__(self, path: str | Path) -> None:
        self._path = Path(path)
        # Ensure parent directory exists.
        self._path.parent.mkdir(parents=True, exist_ok=True)
        # Cache the hash of the last line so we can chain without re-reading.
        self._last_line_hash: str | None = None
        if self._path.exists():
            self._last_line_hash = self._compute_last_line_hash()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _compute_last_line_hash(self) -> str | None:
        """Return SHA-256 of the last non-empty line, or None if file is empty."""
        try:
            with self._path.open("rb") as fh:
                # Efficient seek-to-end scan for the last line.
                fh.seek(0, 2)
                size = fh.tell()
                if size == 0:
                    return None
                # Scan backwards for the last newline.
                chunk_size = min(8192, size)
                fh.seek(-chunk_size, 2)
                data = fh.read()
                lines = data.split(b"\n")
                # Last element may be empty (trailing newline).
                for raw in reversed(lines):
                    raw = raw.strip()
                    if raw:
                        return _sha256_bytes(raw)
                return None
        except OSError:
            return None

    def _prev_hash(self) -> str:
        if self._last_line_hash is None:
            return _GENESIS_PREV
        return self._last_line_hash

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def append(self, record_type: str, *, ts: str | None = None, **fields: Any) -> None:
        """Append a record to the audit log.

        Parameters
        ----------
        record_type : str
            One of: intent, ledger-sealed, entry-written, pending-staged,
            pending-dropped, acknowledged, ratified.
        ts : str | None
            ISO-8601 timestamp (UTC).  Defaults to now.  Supply a fixed
            value in tests for deterministic output.
        **fields
            Extra fields embedded in the record JSON.
        """
        record: dict[str, Any] = {
            "type": record_type,
            "ts": ts or _now_iso(),
            "prev": self._prev_hash(),
        }
        record.update(fields)
        line = json.dumps(record, separators=(",", ":"), sort_keys=True)
        line_bytes = (line + "\n").encode("utf-8")

        with self._path.open("ab") as fh:
            fh.write(line_bytes)
            fh.flush()
            os.fsync(fh.fileno())

        # Update the cached last-line hash.
        self._last_line_hash = _sha256_line(line)

    def tail(self, n: int = 10) -> list[dict]:
        """Return the last *n* records as parsed dicts."""
        if not self._path.exists():
            return []
        records: list[dict] = []
        with self._path.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\n")
                if line.strip():
                    records.append(json.loads(line))
        return records[-n:] if n > 0 else records

    def all_records(self) -> list[dict]:
        """Return all records as parsed dicts."""
        return self.tail(n=0)

    def last_sealed(self) -> dict | None:
        """Return the most-recent ``ledger-sealed`` record.

        Acknowledgement and ratification records may follow the last seal;
        this method skips them to find the true last seal.
        """
        _SKIP_TYPES = {"acknowledged", "ratified"}
        records = self.all_records()
        for record in reversed(records):
            if record.get("type") not in _SKIP_TYPES:
                if record.get("type") == "ledger-sealed":
                    return record
                # Any non-skip type that is not ledger-sealed breaks the search.
                break
        # Second pass: scan all records for the last ledger-sealed.
        for record in reversed(records):
            if record.get("type") == "ledger-sealed":
                return record
        return None

    def last_intent(self) -> dict | None:
        """Return the most-recent ``intent`` record."""
        for record in reversed(self.all_records()):
            if record.get("type") == "intent":
                return record
        return None

    def has_seal_for_intent(self, intent_record: dict) -> bool:
        """Return True when a ``ledger-sealed`` record post-dates *intent_record*.

        "Post-dates" here means: appears later in the log file.
        """
        records = self.all_records()
        intent_ts = intent_record.get("ts", "")
        intent_prev = intent_record.get("prev", "")

        # Find the index of the intent record by matching ts + prev (unique combination).
        intent_idx = None
        for idx, r in enumerate(records):
            if r.get("type") == "intent" and r.get("ts") == intent_ts and r.get("prev") == intent_prev:
                intent_idx = idx
                break

        if intent_idx is None:
            return False

        for r in records[intent_idx + 1:]:
            if r.get("type") == "ledger-sealed":
                return True
        return False


# ---------------------------------------------------------------------------
# Chain verification
# ---------------------------------------------------------------------------


def verify_chain(path: str | Path) -> list[str]:
    """Read *path* and return a list of error strings.

    An empty list means the chain is intact.  Errors include:
    - Corrupted / unparseable JSON lines.
    - A record whose ``prev`` does not match the SHA-256 of the previous line.
    - Missing ``prev`` field.
    """
    p = Path(path)
    if not p.exists():
        return []

    errors: list[str] = []
    prev_hash: str | None = None  # None means we haven't seen any record yet.

    with p.open("r", encoding="utf-8") as fh:
        for line_no, raw_line in enumerate(fh, start=1):
            stripped = raw_line.rstrip("\n")
            if not stripped.strip():
                continue  # Skip blank lines.

            # Parse JSON.
            try:
                record = json.loads(stripped)
            except json.JSONDecodeError as exc:
                errors.append(f"Line {line_no}: invalid JSON — {exc}")
                prev_hash = _sha256_line(stripped)
                continue

            # Check prev field.
            expected_prev = prev_hash if prev_hash is not None else _GENESIS_PREV
            actual_prev = record.get("prev")

            if actual_prev is None:
                errors.append(f"Line {line_no}: missing 'prev' field in record type={record.get('type')!r}")
            elif actual_prev != expected_prev:
                errors.append(
                    f"Line {line_no}: chain broken — expected prev={expected_prev!r}, "
                    f"got {actual_prev!r} (type={record.get('type')!r})"
                )

            prev_hash = _sha256_line(stripped)

    return errors
